- name: Reboot RHEL Servers (Ending with 01)
  hosts: ending_01
  gather_facts: no
  serial: 15
  tasks:
    - name: Optional pause before reboot
      pause:
        minutes: 1
      when: ims_srr_disabled is defined

    - name: Reboot server if IMS SRR is disabled
      when: ims_srr_disabled | default(false)
      block:
        - name: Reboot the server
          reboot:
            reboot_timeout: 600
            post_reboot_delay: 60
          become: true

        - name: Display reboot completion message
          debug:
            msg: "{{ inventory_hostname }} - Server rebooted successfully."

    - name: Output if reboot is skipped
      debug:
        msg: "Server {{ inventory_hostname }} skipped reboot because IMS SRR is not disabled."
      when: not (ims_srr_disabled | default(false))
