- name: Group RHEL Servers (Ending with 01)
  hosts: all
  gather_facts: no
  tasks:
    - name: Group servers by ending
      add_host:
        name: "{{ item }}"
        groups: "ending_{{ item[-2:] }}"
      loop: "{{ play_hosts }}"

- name: Reboot RHEL Servers (Ending with 01)
  hosts: ending_01
  gather_facts: no
  serial: 15
  tasks:
    - name: Check for no new jobs
      shell: >
        tail -f `ls -1t /var/log/cloudstor_manager/manager* | head -1` 
        | awk '/No new jobs found.../{printf "."};!/No new/{print $0; exit 1}' 
        | timeout 30 tr -d '\n'  # Remove newlines for counting dots
      register: log_output
      failed_when: false
      changed_when: false
    
    - name: Show log output
      debug:
        msg: "output: {{ log_output }}"

    - name: Extract dots only from log output
      set_fact:
        extracted_dots: "{{ log_output.stdout | regex_replace('[^.]', '') }}"

    - name: Count dots
      set_fact:
        dot_count: "{{ extracted_dots | length }}"

    - name: Check if log contains only dots
      set_fact:
        contains_only_dots: "{{ log_output.stdout | regex_search('^[.]+$', multiline=True) is not none }}"

    - name: Display log validation status
      debug:
        msg: "Contains only dots: {{ contains_only_dots }}"

    - name: Optional pause before reboot
      pause:
        minutes: 1  # Optional delay; remove if not needed
      when: ims_srr_disabled is defined  # Only pause if the variable is provided

    - name: Reboot server if conditions are met
      when: contains_only_dots and (dot_count | int >= 7) and (ims_srr_disabled | default(false))
      block:
        - name: Reboot the server
          reboot:
            reboot_timeout: 600  # Wait up to 10 minutes for reboot
            post_reboot_delay: 60  # Wait 60 seconds after reboot before checking
          become: true

        - name: Display reboot completion message
          debug:
            msg: "{{ inventory_hostname }} - Server rebooted successfully."

    - name: Output if reboot is skipped
      debug:
        msg: "Server {{ inventory_hostname }} skipped reboot due to invalid log output, insufficient dots, or IMS SRR not disabled."
      when: not contains_only_dots or (dot_count | int < 7) or not (ims_srr_disabled | default(false))
