- name: Group RHEL Servers (Ending with 01)
  hosts: all
  gather_facts: no
  tasks:
    - name: Group servers by ending
      add_host:
        name: "{{ item }}"
        groups: "ending_{{ item[-2:] }}"
      loop: "{{ play_hosts }}"

- name: Validate RHEL Servers (Ending with 01)
  hosts: ending_01
  gather_facts: no
  serial: 15
  tasks:
    - name: Check for no new jobs
      shell: >
        tail -f `ls -1t /var/log/cloudstor_manager/manager* | head -1` 
        | awk '/No new jobs found.../{printf "."};!/No new/{print $0; exit 1}' 
        | timeout 30 tr -d '\n'
      register: log_output
      failed_when: false
      changed_when: false
    
    - name: Show log output
      debug:
        msg: "output: {{ log_output }}"

    - name: Extract dots only from log output
      set_fact:
        extracted_dots: "{{ log_output.stdout | regex_replace('[^.]', '') }}"

    - name: Count dots
      set_fact:
        dot_count: "{{ extracted_dots | length }}"

    - name: Debug dot count
      debug:
        msg: "Dot count: {{ dot_count }}"

    - name: Check if log contains only dots
      set_fact:
        contains_only_dots: "{{ log_output.stdout | regex_search('^[.]+$', multiline=True) is not none }}"

    - name: Display log validation status
      debug:
        msg: "Contains only dots: {{ contains_only_dots }}"
