- name: Patch RHEL Servers
  hosts: all
  gather_facts: no
  tasks:
    - name: Group servers by ending
      add_host:
        name: "{{ item }}"
        groups: "ending_{{ item[-2:] }}"
      loop: "{{ play_hosts }}"

# Check for no new jobs and patch servers ending with 01
- name: Check for no new jobs and patch servers ending with 01
  hosts: ending_01
  gather_facts: yes
  serial: 15
  tasks:
    - name: Run the script to generate dots for 15 seconds
      shell: "/home/yash/generate_dots.sh"
      async: 15
      poll: 0
      register: dot_generation_job

    - name: Wait for 15 seconds for the script to complete
      wait_for:
        timeout: 15

    - name: Check for dots in the dummy log file
      shell: "tail -n 100 /tmp/dummy_log.txt | grep -o '.' | wc -l"
      register: job_check
      failed_when: false
      changed_when: false

    - name: Debug job_check.stdout
      debug:
        var: job_check.stdout

    - name: Count dots in output
      set_fact:
        dot_count: "{{ job_check.stdout | trim | int }}"

    - name: Debug dot_count
      debug:
        var: dot_count

    - name: Pause for 30 minutes after dot count
      pause:
        minutes: 30
      register: pause_result
      when: "'ansible_job_id' not in ansible_env"  # Skips pause if running from Jenkins with interrupt

    - name: Decide action based on dot count
      block:
        - name: Apply security updates
          shell: yum update -y
          register: YUM_OUT
          async: 3600
          poll: 60
          become: true

        - debug: var=YUM_OUT.stdout_lines

        - name: Install prereqs
          yum:
            name: yum-utils
            state: installed
          become: true

        - name: Check if we need to restart
          shell: /usr/bin/needs-restarting -r | grep -i reboot
          check_mode: no
          register: needs_restarting_out
          failed_when: ( needs_restarting_out.rc not in [ 0, 1 ] )
          changed_when: False
          become: true

        - debug: var=needs_restarting_out.stdout_lines

        - name: Display update completion message
          debug:
            msg: "{{ ansible_nodename }} - Security updates applied. {{ needs_restarting_out.stdout }}"
      when: dot_count | int >= 7

    - name: Output jobs are running
      debug:
        msg: "Server {{ inventory_hostname }} has jobs running, skipping patch."
      when: dot_count | int < 7

- name: Pause before processing ending_02
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Pause for 30 minutes before next group
      pause:
        minutes: 30
      when: "'ansible_job_id' not in ansible_env"  # Skips pause if running from Jenkins with interrupt

# Check for no new jobs and patch servers ending with 02
- name: Check for no new jobs and patch servers ending with 02
  hosts: ending_02
  gather_facts: yes
  serial: 15
  tasks:
    - name: Run the script to generate dots for 15 seconds
      shell: "/home/yash/generate_dots.sh"
      async: 15
      poll: 0
      register: dot_generation_job

    - name: Wait for 15 seconds for the script to complete
      wait_for:
        timeout: 15

    - name: Check for dots in the dummy log file
      shell: "tail -n 100 /tmp/dummy_log.txt | grep -o '.' | wc -l"
      register: job_check
      failed_when: false
      changed_when: false

    - name: Debug job_check.stdout
      debug:
        var: job_check.stdout

    - name: Count dots in output
      set_fact:
        dot_count: "{{ job_check.stdout | trim | int }}"

    - name: Debug dot_count
      debug:
        var: dot_count

    - name: Pause for 30 minutes after dot count
      pause:
        minutes: 30
      register: pause_result
      when: "'ansible_job_id' not in ansible_env"  # Skips pause if running from Jenkins with interrupt

    - name: Decide action based on dot count
      block:
        - name: Apply security updates
          shell: yum update -y
          register: YUM_OUT
          async: 3600
          poll: 60
          become: true

        - debug: var=YUM_OUT.stdout_lines

        - name: Install prereqs
          yum:
            name: yum-utils
            state: installed
          become: true

        - name: Check if we need to restart
          shell: /usr/bin/needs-restarting -r | grep -i reboot
          check_mode: no
          register: needs_restarting_out
          failed_when: ( needs_restarting_out.rc not in [ 0, 1 ] )
          changed_when: False
          become: true

        - debug: var=needs_restarting_out.stdout_lines

        - name: Display update completion message
          debug:
            msg: "{{ ansible_nodename }} - Security updates applied. {{ needs_restarting_out.stdout }}"
      when: dot_count | int >= 7

    - name: Output jobs are running
      debug:
        msg: "Server {{ inventory_hostname }} has jobs running, skipping patch."
      when: dot_count | int < 7

- name: Pause before processing ending_03
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Pause for 30 minutes before next group
      pause:
        minutes: 30
      when: "'ansible_job_id' not in ansible_env"  # Skips pause if running from Jenkins with interrupt

# Check for no new jobs and patch servers ending with 03
- name: Check for no new jobs and patch servers ending with 03
  hosts: ending_03
  gather_facts: yes
  serial: 15
  tasks:
    - name: Run the script to generate dots for 15 seconds
      shell: "/home/yash/generate_dots.sh"
      async: 15
      poll: 0
      register: dot_generation_job

    - name: Wait for 15 seconds for the script to complete
      wait_for:
        timeout: 15

    - name: Check for dots in the dummy log file
      shell: "tail -n 100 /tmp/dummy_log.txt | grep -o '.' | wc -l"
      register: job_check
      failed_when: false
      changed_when: false

    - name: Debug job_check.stdout
      debug:
        var: job_check.stdout

    - name: Count dots in output
      set_fact:
        dot_count: "{{ job_check.stdout | trim | int }}"

    - name: Debug dot_count
      debug:
        var: dot_count

    - name: Pause for 30 minutes after dot count
      pause:
        minutes: 30
      register: pause_result
      when: "'ansible_job_id' not in ansible_env"  # Skips pause if running from Jenkins with interrupt

    - name: Decide action based on dot count
      block:
        - name: Apply security updates
          shell: yum update -y
          register: YUM_OUT
          async: 3600
          poll: 60
          become: true

        - debug: var=YUM_OUT.stdout_lines

        - name: Install prereqs
          yum:
            name: yum-utils
            state: installed
          become: true

        - name: Check if we need to restart
          shell: /usr/bin/needs-restarting -r | grep -i reboot
          check_mode: no
          register: needs_restarting_out
          failed_when: ( needs_restarting_out.rc not in [ 0, 1 ] )
          changed_when: False
          become: true

        - debug: var=needs_restarting_out.stdout_lines

        - name: Display update completion message
          debug:
            msg: "{{ ansible_nodename }} - Security updates applied. {{ needs_restarting_out.stdout }}"
      when: dot_count | int >= 7

    - name: Output jobs are running
      debug:
        msg: "Server {{ inventory_hostname }} has jobs running, skipping patch."
      when: dot_count | int < 7
