- name: Patch RHEL Servers (Ending with 01)
  hosts: all
  gather_facts: no
  tasks:
    - name: Group servers by ending
      add_host:
        name: "{{ item }}"
        groups: "ending_{{ item[-2:] }}"
      loop: "{{ play_hosts }}"

- name: Patch RHEL Servers (Ending with 01)
  hosts: ending_01
  gather_facts: no
  serial: 15
  tasks:
    - name: Run the script to generate dots for 15 seconds
      shell: "/home/yash/generate_dots.sh"
      async: 15
      poll: 0
      register: dot_generation_job

    - name: Wait for 15 seconds
      wait_for:
        timeout: 15

    - name: Capture dot output
      shell: "tail -n 100 /tmp/dummy_log.txt"
      register: log_output
      changed_when: false
      failed_when: false

    - name: Extract dots only
      set_fact:
        extracted_dots: "{{ log_output.stdout | regex_replace('[^.]', '') }}"

    - name: Count dots
      set_fact:
        dot_count: "{{ extracted_dots | length }}"

    - name: Display dot count
      debug:
        msg: "Dot count before patching: {{ dot_count }}"

    - name: Check if log contains only dots
      set_fact:
        contains_only_dots: "{{ log_output.stdout | regex_search('^[.]+$', multiline=True) is not none }}"

    - name: Display log validation status
      debug:
        msg: "Contains only dots: {{ contains_only_dots }}"

    - name: Pause for 30 minutes before patching
      pause:
        minutes: 1

    - name: Apply security updates if log contains only dots and has at least 7 dots
      when: contains_only_dots and (dot_count | int >= 7)
      block:
        - name: Apply security updates
          yum:
            name: '*'
            state: latest
          become: true

        - name: Install prerequisite packages
          yum:
            name: yum-utils
            state: installed
          become: true

        - name: Check if we need to restart
          shell: /usr/bin/needs-restarting -r | grep -i reboot
          check_mode: no
          register: needs_restarting_out
          failed_when: ( needs_restarting_out.rc not in [ 0, 1 ] )
          changed_when: False
          become: true

        - debug: var=needs_restarting_out.stdout_lines

        - name: Display update completion message
          debug:
            msg: "{{ inventory_hostname }} - Security updates applied. {{ needs_restarting_out.stdout }}"

    - name: Output if patching is skipped
      debug:
        msg: "Server {{ inventory_hostname }} skipped patching due to invalid log output or insufficient dots."
      when: not contains_only_dots or (dot_count | int < 7)
