- name: Reboot specific HAP host
  hosts: all
  gather_facts: no
  tasks:
    - name: Reboot the host
      reboot:
        msg: "Reboot initiated"
        pre_reboot_delay: 5
        post_reboot_delay: 60
        test_command: uptime
      become: true

    - name: Wait for connection
      wait_for_connection:
        delay: 10
        timeout: 120

    - name: Confirm reboot success
      debug:
        msg: "{{ inventory_hostname }} rebooted successfully."


