- name: Reboot specific host
  hosts: "{{ target_host }}"
  gather_facts: no
  tasks:
    - name: Reboot the server
      reboot:
        msg: "Reboot initiated"
        pre_reboot_delay: 5
        post_reboot_delay: 60
        test_command: uptime
      become: true

    - name: Wait for server to come online 
      wait_for_connection:
        delay: 10
        timeout: 120

    - name: Display reboot completion message
      debug:
        msg: "{{ inventory_hostname }} - Server rebooted successfully."


